In [2]:
import extract
print(extract.__file__)

c:\work\data-migration-aparna\extract.py

In [3]:
from extract import extract

In [4]:
customers_df = extract("customers")

In [5]:
customers_df.head()

,customer_id,profile,address,payment_methods,last_updated
0,CUST001,"{'name': 'Customer_1', 'email': 'customer1@exa...","{'current': {'street': 'Street 112', 'city': '...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-02-26T04:20:23.360672
1,CUST002,"{'name': 'Customer_2', 'email': 'customer2@exa...","{'current': {'street': 'Street 83', 'city': 'H...","[{'method': 'Credit Card', 'provider': 'HDFC',...",2026-02-26T13:20:23.360728
2,CUST003,"{'name': 'Customer_3', 'email': 'customer3@exa...","{'current': {'street': 'Street 125', 'city': '...","[{'method': 'Debit Card', 'provider': 'SBI', '...",2026-02-24T04:20:23.360752
3,CUST004,"{'name': 'Customer_4', 'email': 'customer4@exa...","{'current': {'street': 'Street 88', 'city': 'K...","[{'method': 'UPI', 'provider': 'SBI', 'last_us...",2026-02-23T08:20:23.360773
4,CUST005,"{'name': 'Customer_5', 'email': 'customer5@exa...","{'current': {'street': 'Street 4', 'city': 'Ko...","[{'method': 'Debit Card', 'provider': 'HDFC', ...",2026-02-20T10:20:23.360790

In [6]:
orders_df = extract("orders")

In [7]:
orders_df

,order_id,customer_id,seller_id,order_date,order_status,items,payment,shipping,order_total,last_updated
0,ORD0001,CUST173,SELL068,2026-02-15T14:30:28.025493,DELIVERED,"[{'product_id': 'PRD426', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN564118...","{'delivery_partner': 'Delhivery', 'expected_de...",66057.93,2026-02-17T05:30:28.025493
1,ORD0002,CUST110,SELL035,2026-02-11T14:30:28.025584,CANCELLED,"[{'product_id': 'PRD134', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN294309...","{'delivery_partner': None, 'expected_delivery'...",70345.25,2026-02-12T06:30:28.025584
2,ORD0003,CUST429,SELL017,2026-02-07T14:30:28.025646,PLACED,"[{'product_id': 'PRD756', 'product_name': 'Clo...","{'method': 'Credit Card', 'transaction_id': 'T...","{'delivery_partner': 'Delhivery', 'expected_de...",26484.62,2026-02-08T01:30:28.025646
3,ORD0004,CUST344,SELL029,2026-02-11T14:30:28.025703,PLACED,"[{'product_id': 'PRD915', 'product_name': 'Boo...","{'method': 'UPI', 'transaction_id': 'TXN455540...","{'delivery_partner': 'Delhivery', 'expected_de...",125493.68,2026-02-13T06:30:28.025703
4,ORD0005,CUST437,SELL056,2026-02-14T14:30:28.025751,PLACED,"[{'product_id': 'PRD651', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN680412...","{'delivery_partner': 'Delhivery', 'expected_de...",54059.38,2026-02-15T03:30:28.025751
...,...,...,...,...,...,...,...,...,...,...
1495,ORD1496,CUST212,SELL102,2026-01-29T14:30:28.074240,SHIPPED,"[{'product_id': 'PRD247', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN604123...","{'delivery_partner': 'Delhivery', 'expected_de...",28465.30,2026-01-30T02:30:28.074240
1496,ORD1497,CUST113,SELL084,2026-02-14T14:30:28.074276,DELIVERED,"[{'product_id': 'PRD810', 'product_name': 'Hom...","{'method': 'Debit Card', 'transaction_id': Non...","{'delivery_partner': 'Ecom Express', 'expected...",115995.38,2026-02-14T17:30:28.074276
1497,ORD1498,CUST340,SELL048,2026-02-21T14:30:28.074306,CANCELLED,"[{'product_id': 'PRD363', 'product_name': 'Hom...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'Ecom Express', 'expected...",124713.88,2026-02-21T21:30:28.074306
1498,ORD1499,CUST335,SELL067,2026-01-31T14:30:28.074331,CANCELLED,"[{'product_id': 'PRD875', 'product_name': 'Boo...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'Delhivery', 'expected_de...",3095.16,2026-02-01T15:30:28.074331
1499,ORD1500,CUST307,SELL080,2026-02-03T14:30:28.074352,CANCELLED,"[{'product_id': 'PRD436', 'product_name': 'Ele...","{'method': 'UPI', 'transaction_id': 'TXN595317...","{'delivery_partner': 'Ecom Express', 'expected...",19629.21,2026-02-04T06:30:28.074352

In [8]:
sellers_df=extract("sellers")

In [9]:
sellers_df.head()

,seller_id,seller_profile,address,products,ratings,performance,last_updated
0,SELL001,"{'name': 'Seller_1', 'business_type': 'Wholesa...","{'street': 'Shop 155', 'city': 'Pune', 'state'...","[{'product_id': 'PRD866', 'category': 'Electro...","[{'customer_id': 'CUST014', 'rating': 1, 'revi...","{'total_orders': 1407, 'cancelled_orders': 5}",2026-02-23T22:23:37.884927
1,SELL002,"{'name': 'Seller_2', 'business_type': None, 'j...","{'street': 'Shop 280', 'city': 'Delhi', 'state...","[{'product_id': 'PRD528', 'category': 'Books',...","[{'customer_id': 'CUST082', 'rating': 4, 'revi...","{'total_orders': 151, 'cancelled_orders': None}",2026-02-22T12:23:37.885053
2,SELL003,"{'name': 'Seller_3', 'business_type': 'Retail'...","{'street': 'Shop 298', 'city': 'Kolkata', 'sta...","[{'product_id': 'PRD555', 'category': 'Clothin...","[{'customer_id': 'CUST352', 'rating': 4, 'revi...","{'total_orders': 856, 'cancelled_orders': 8}",2026-02-24T15:23:37.885148
3,SELL004,"{'name': 'Seller_4', 'business_type': 'Retail'...","{'street': 'Shop 83', 'city': 'Mumbai', 'state...","[{'product_id': 'PRD833', 'category': 'Books',...","[{'customer_id': 'CUST261', 'rating': 3, 'revi...","{'total_orders': 425, 'cancelled_orders': 8}",2026-02-20T23:23:37.885277
4,SELL005,"{'name': 'Seller_5', 'business_type': 'Retail'...","{'street': 'Shop 217', 'city': 'Pune', 'state'...","[{'product_id': 'PRD831', 'category': 'Books',...","[{'customer_id': 'CUST241', 'rating': 1, 'revi...","{'total_orders': 1403, 'cancelled_orders': 20}",2026-02-20T01:23:37.885400

In [10]:
from extract import extract
customers_df = extract("customers")
sellers_df   = extract("sellers")
orders_df = extract("orders")

In [11]:
customers_df.head(5)

,customer_id,profile,address,payment_methods,last_updated
0,CUST001,"{'name': 'Customer_1', 'email': 'customer1@exa...","{'current': {'street': 'Street 112', 'city': '...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-02-26T04:20:23.360672
1,CUST002,"{'name': 'Customer_2', 'email': 'customer2@exa...","{'current': {'street': 'Street 83', 'city': 'H...","[{'method': 'Credit Card', 'provider': 'HDFC',...",2026-02-26T13:20:23.360728
2,CUST003,"{'name': 'Customer_3', 'email': 'customer3@exa...","{'current': {'street': 'Street 125', 'city': '...","[{'method': 'Debit Card', 'provider': 'SBI', '...",2026-02-24T04:20:23.360752
3,CUST004,"{'name': 'Customer_4', 'email': 'customer4@exa...","{'current': {'street': 'Street 88', 'city': 'K...","[{'method': 'UPI', 'provider': 'SBI', 'last_us...",2026-02-23T08:20:23.360773
4,CUST005,"{'name': 'Customer_5', 'email': 'customer5@exa...","{'current': {'street': 'Street 4', 'city': 'Ko...","[{'method': 'Debit Card', 'provider': 'HDFC', ...",2026-02-20T10:20:23.360790

In [12]:
sellers_df.head()

,seller_id,seller_profile,address,products,ratings,performance,last_updated
0,SELL001,"{'name': 'Seller_1', 'business_type': 'Wholesa...","{'street': 'Shop 155', 'city': 'Pune', 'state'...","[{'product_id': 'PRD866', 'category': 'Electro...","[{'customer_id': 'CUST014', 'rating': 1, 'revi...","{'total_orders': 1407, 'cancelled_orders': 5}",2026-02-23T22:23:37.884927
1,SELL002,"{'name': 'Seller_2', 'business_type': None, 'j...","{'street': 'Shop 280', 'city': 'Delhi', 'state...","[{'product_id': 'PRD528', 'category': 'Books',...","[{'customer_id': 'CUST082', 'rating': 4, 'revi...","{'total_orders': 151, 'cancelled_orders': None}",2026-02-22T12:23:37.885053
2,SELL003,"{'name': 'Seller_3', 'business_type': 'Retail'...","{'street': 'Shop 298', 'city': 'Kolkata', 'sta...","[{'product_id': 'PRD555', 'category': 'Clothin...","[{'customer_id': 'CUST352', 'rating': 4, 'revi...","{'total_orders': 856, 'cancelled_orders': 8}",2026-02-24T15:23:37.885148
3,SELL004,"{'name': 'Seller_4', 'business_type': 'Retail'...","{'street': 'Shop 83', 'city': 'Mumbai', 'state...","[{'product_id': 'PRD833', 'category': 'Books',...","[{'customer_id': 'CUST261', 'rating': 3, 'revi...","{'total_orders': 425, 'cancelled_orders': 8}",2026-02-20T23:23:37.885277
4,SELL005,"{'name': 'Seller_5', 'business_type': 'Retail'...","{'street': 'Shop 217', 'city': 'Pune', 'state'...","[{'product_id': 'PRD831', 'category': 'Books',...","[{'customer_id': 'CUST241', 'rating': 1, 'revi...","{'total_orders': 1403, 'cancelled_orders': 20}",2026-02-20T01:23:37.885400

In [13]:
orders_df.head()

,order_id,customer_id,seller_id,order_date,order_status,items,payment,shipping,order_total,last_updated
0,ORD0001,CUST173,SELL068,2026-02-15T14:30:28.025493,DELIVERED,"[{'product_id': 'PRD426', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN564118...","{'delivery_partner': 'Delhivery', 'expected_de...",66057.93,2026-02-17T05:30:28.025493
1,ORD0002,CUST110,SELL035,2026-02-11T14:30:28.025584,CANCELLED,"[{'product_id': 'PRD134', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN294309...","{'delivery_partner': None, 'expected_delivery'...",70345.25,2026-02-12T06:30:28.025584
2,ORD0003,CUST429,SELL017,2026-02-07T14:30:28.025646,PLACED,"[{'product_id': 'PRD756', 'product_name': 'Clo...","{'method': 'Credit Card', 'transaction_id': 'T...","{'delivery_partner': 'Delhivery', 'expected_de...",26484.62,2026-02-08T01:30:28.025646
3,ORD0004,CUST344,SELL029,2026-02-11T14:30:28.025703,PLACED,"[{'product_id': 'PRD915', 'product_name': 'Boo...","{'method': 'UPI', 'transaction_id': 'TXN455540...","{'delivery_partner': 'Delhivery', 'expected_de...",125493.68,2026-02-13T06:30:28.025703
4,ORD0005,CUST437,SELL056,2026-02-14T14:30:28.025751,PLACED,"[{'product_id': 'PRD651', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN680412...","{'delivery_partner': 'Delhivery', 'expected_de...",54059.38,2026-02-15T03:30:28.025751

In [14]:
from transform import transform

In [15]:
dir(transform)

['__annotate__',
 '__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__type_params__']

In [16]:
customers_df = transform(customers_df)
customers_df.head(2)

,customer_id,last_updated,method,provider,last_used,profile_name,profile_email,profile_phone,profile_status,profile_signup_date,address_current_street,address_current_city,address_current_state,address_current_zip,address_current_country
0,CUST001,2026-02-26T04:20:23.360672,Credit Card,ICICI,2026-02-06,Customer_1,customer1@example.com,9631006637,ACTIVE,2026-01-08T14:20:23.360704,Street 112,Hyderabad,Telangana,827822,India
1,CUST002,2026-02-26T13:20:23.360728,Credit Card,HDFC,2026-01-31,Customer_2,customer2@example.com,9655021673,INACTIVE,2025-03-12T14:20:23.360736,Street 83,Hyderabad,Telangana,846888,India

In [17]:
sellers_df_transform=transform(sellers_df)
sellers_df_transform.head(2)

,seller_id,last_updated,product_id,category,price,stock,customer_id,rating,review,review_date,seller_profile_name,seller_profile_business_type,seller_profile_joined_date,address_street,address_city,address_state,address_zip,address_country,performance_total_orders,performance_cancelled_orders
0,SELL001,2026-02-23T22:23:37.884927,PRD866,Electronics,15109.81,183.0,CUST014,1,Auto generated review,2026-01-12,Seller_1,Wholesale,2024-04-04,Shop 155,Pune,Maharashtra,787212,India,1407,5.0
1,SELL001,2026-02-23T22:23:37.884927,PRD866,Electronics,15109.81,183.0,CUST181,2,NaN,2026-02-06,Seller_1,Wholesale,2024-04-04,Shop 155,Pune,Maharashtra,787212,India,1407,5.0

In [18]:
orders_df.head(2)

,order_id,customer_id,seller_id,order_date,order_status,items,payment,shipping,order_total,last_updated
0,ORD0001,CUST173,SELL068,2026-02-15T14:30:28.025493,DELIVERED,"[{'product_id': 'PRD426', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN564118...","{'delivery_partner': 'Delhivery', 'expected_de...",66057.93,2026-02-17T05:30:28.025493
1,ORD0002,CUST110,SELL035,2026-02-11T14:30:28.025584,CANCELLED,"[{'product_id': 'PRD134', 'product_name': 'Clo...","{'method': 'UPI', 'transaction_id': 'TXN294309...","{'delivery_partner': None, 'expected_delivery'...",70345.25,2026-02-12T06:30:28.025584

In [19]:
orders_df_transform=transform(orders_df)
orders_df_transform.head(2)

,order_id,customer_id,seller_id,order_date,order_status,order_total,last_updated,product_id,product_name,quantity,price,discount_type,discount_amount,payment_method,payment_transaction_id,payment_payment_status,shipping_delivery_partner,shipping_expected_delivery
0,ORD0001,CUST173,SELL068,2026-02-15T14:30:28.025493,DELIVERED,66057.93,2026-02-17T05:30:28.025493,PRD426,Clothing,2,12601.74,FLAT,200.0,UPI,TXN564118,SUCCESS,Delhivery,2026-02-22
1,ORD0001,CUST173,SELL068,2026-02-15T14:30:28.025493,DELIVERED,66057.93,2026-02-17T05:30:28.025493,PRD426,Clothing,1,12601.74,FLAT,50.0,UPI,TXN564118,SUCCESS,Delhivery,2026-02-22