In [2]:
import extract
print(extract.__file__)

c:\work\data-migration-aparna\extract.py

In [3]:
from extract import extract

In [4]:
customers_df = extract("customers")

In [5]:
customers_df.head()

,_id,customer_id,profile,address,payment_methods,last_updated
0,69a8ff7c8aa490a18f20b688,CUST001,"{'name': 'Customer_0A1', 'email': 'customer1@e...","{'current': {'street': None, 'city': 'Mumbai',...","[{'method': 'Credit Card', 'provider': 'SBI', ...",2026-03-06T00:28:20.082640
1,69a8ff7c8aa490a18f20b689,CUST002,"{'name': 'Customer_2', 'email': 'customer2@exa...","{'current': {'street': 'Street 153', 'city': '...","[{'method': 'Debit Card', 'provider': 'ICICI',...",2026-03-03T00:28:20.082706
2,69a8ff7c8aa490a18f20b68a,CUST003,"{'name': 'Customer_3', 'email': 'customer3@exa...","{'current': {'street': None, 'city': 'Chennai'...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-03-01T00:28:20.082744
3,69a8ff7c8aa490a18f20b68b,CUST004,"{'name': 'Customer_4', 'email': 'customer4@exa...","{'current': {'street': 'Street 200', 'city': '...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-03-03T00:28:20.082767
4,69a8ff7c8aa490a18f20b68c,CUST005,"{'name': 'Customer_5', 'email': 'customer5@exa...","{'current': {'street': None, 'city': 'Hyderaba...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-03-04T00:28:20.082786

In [6]:
orders_df = extract("orders")

In [7]:
orders_df

,_id,order_id,customer_id,seller_id,order_date,order_status,items,payment,shipping,order_total,last_updated
0,69a8ff7d8aa490a18f20b8f4,ORD0001,CUST498,SELL105,2026-02-13T09:28:40.374751,PLACED,"[{'product_id': 'SELL105_PRD5', 'product_name'...","{'method': 'UPI', 'transaction_id': None, 'pay...","{'delivery_partner': 'BlueDart', 'expected_del...",33993.48,2026-02-14T06:28:40.374751
1,69a8ff7d8aa490a18f20b8f5,ORD0002,CUST223,SELL022,2026-02-22T09:28:40.374846,CANCELLED,"[{'product_id': 'SELL022_PRD5', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'Delhivery', 'expected_de...",94373.34,2026-02-23T09:28:40.374846
2,69a8ff7d8aa490a18f20b8f6,ORD0003,CUST186,SELL081,2026-02-17T09:28:40.374898,SHIPPED,"[{'product_id': 'SELL081_PRD3', 'product_name'...","{'method': 'Credit Card', 'transaction_id': 'T...","{'delivery_partner': 'Ecom Express', 'expected...",91000.23,2026-02-18T11:28:40.374898
3,69a8ff7d8aa490a18f20b8f7,ORD0004,CUST357,SELL012,2026-02-05T09:28:40.374938,CANCELLED,"[{'product_id': 'SELL012_PRD3', 'product_name'...","{'method': 'Credit Card', 'transaction_id': 'T...","{'delivery_partner': 'Delhivery', 'expected_de...",NaN,2026-02-06T07:28:40.374938
4,69a8ff7d8aa490a18f20b8f8,ORD0005,CUST359,SELL120,2026-02-11T09:28:40.374991,NaN,"[{'product_id': 'SELL120_PRD5', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'BlueDart', 'expected_del...",106526.26,2026-02-12T11:28:40.374991
...,...,...,...,...,...,...,...,...,...,...,...
1495,69a8ff7d8aa490a18f20becb,ORD1496,CUST270,SELL030,2026-02-08T09:28:40.438104,PLACED,"[{'product_id': 'SELL030_PRD3', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'BlueDart', 'expected_del...",89229.51,2026-02-10T08:28:40.438104
1496,69a8ff7d8aa490a18f20becc,ORD1497,CUST133,SELL011,2026-02-10T09:28:40.438132,DELIVERED,"[{'product_id': 'SELL011_PRD3', 'product_name'...","{'method': 'Credit Card', 'transaction_id': 'T...","{'delivery_partner': 'Delhivery', 'expected_de...",26405.95,2026-02-10T23:28:40.438132
1497,69a8ff7d8aa490a18f20becd,ORD1498,CUST212,SELL052,2026-02-16T09:28:40.438163,DELIVERED,"[{'product_id': 'SELL052_PRD2', 'product_name'...","{'method': 'UPI', 'transaction_id': 'TXN960605...","{'delivery_partner': 'Ecom Express', 'expected...",29616.80,2026-02-18T03:28:40.438163
1498,69a8ff7d8aa490a18f20bece,ORD1499,CUST305,SELL118,2026-02-25T09:28:40.438191,DELIVERED,"[{'product_id': 'SELL118_PRD1', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'BlueDart', 'expected_del...",50309.30,2026-02-27T06:28:40.438191
1499,69a8ff7d8aa490a18f20becf,ORD1500,CUST062,SELL065,2026-02-08T09:28:40.438226,SHIPPED,"[{'product_id': 'SELL065_PRD5', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'Ecom Express', 'expected...",79561.55,2026-02-08T23:28:40.438226

In [8]:
sellers_df=extract("sellers")

In [9]:
sellers_df.head()

,_id,seller_id,seller_profile,address,products,ratings,performance,last_updated
0,69a8ff7d8aa490a18f20b87c,SELL001,"{'name': 'Seller_1', 'business_type': 'Wholesa...","{'street': 'Shop 279', 'city': 'Bengaluru', 's...","[{'product_id': 'SELL001_PRD1', 'category': 'B...","[{'customer_id': 'CUST118', 'rating': 3, 'revi...","{'total_orders': 920, 'cancelled_orders': 16}",2026-03-04T01:28:30.404844
1,69a8ff7d8aa490a18f20b87d,SELL002,"{'name': 'Seller_2', 'business_type': 'Retail'...","{'street': 'Shop 35', 'city': 'Chennai', 'stat...","[{'product_id': 'SELL002_PRD1', 'category': 'E...","[{'customer_id': 'CUST122', 'rating': 5, 'revi...","{'total_orders': 146, 'cancelled_orders': 5}",2026-03-02T10:28:30.404920
2,69a8ff7d8aa490a18f20b87e,SELL003,"{'name': 'Seller_3', 'business_type': 'Retail'...","{'street': 'Shop 247', 'city': 'Mumbai', 'stat...","[{'product_id': 'SELL003_PRD1', 'category': 'H...","[{'customer_id': 'CUST039', 'rating': 4, 'revi...","{'total_orders': 1845, 'cancelled_orders': 2}",2026-02-26T00:28:30.405011
3,69a8ff7d8aa490a18f20b87f,SELL004,"{'name': 'Seller_4', 'business_type': 'Retail'...","{'street': None, 'city': 'Bengaluru', 'state':...","[{'product_id': 'SELL004_PRD1', 'category': 'E...","[{'customer_id': 'CUST497', 'rating': 5, 'revi...","{'total_orders': 162, 'cancelled_orders': 22}",2026-02-28T17:28:30.405143
4,69a8ff7d8aa490a18f20b880,SELL005,"{'name': 'Seller_5', 'business_type': 'Wholesa...","{'street': 'Shop 53', 'city': 'Bengaluru', 'st...","[{'product_id': 'SELL005_PRD1', 'category': 'H...","[{'customer_id': 'CUST314', 'rating': 3, 'revi...","{'total_orders': 1115, 'cancelled_orders': 50}",2026-03-03T16:28:30.405206

In [10]:
from extract import extract
customers_df = extract("customers")
sellers_df   = extract("sellers")
orders_df = extract("orders")

In [11]:
customers_df.head(5)

,_id,customer_id,profile,address,payment_methods,last_updated
0,69a8ff7c8aa490a18f20b688,CUST001,"{'name': 'Customer_0A1', 'email': 'customer1@e...","{'current': {'street': None, 'city': 'Mumbai',...","[{'method': 'Credit Card', 'provider': 'SBI', ...",2026-03-06T00:28:20.082640
1,69a8ff7c8aa490a18f20b689,CUST002,"{'name': 'Customer_2', 'email': 'customer2@exa...","{'current': {'street': 'Street 153', 'city': '...","[{'method': 'Debit Card', 'provider': 'ICICI',...",2026-03-03T00:28:20.082706
2,69a8ff7c8aa490a18f20b68a,CUST003,"{'name': 'Customer_3', 'email': 'customer3@exa...","{'current': {'street': None, 'city': 'Chennai'...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-03-01T00:28:20.082744
3,69a8ff7c8aa490a18f20b68b,CUST004,"{'name': 'Customer_4', 'email': 'customer4@exa...","{'current': {'street': 'Street 200', 'city': '...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-03-03T00:28:20.082767
4,69a8ff7c8aa490a18f20b68c,CUST005,"{'name': 'Customer_5', 'email': 'customer5@exa...","{'current': {'street': None, 'city': 'Hyderaba...","[{'method': 'Credit Card', 'provider': 'ICICI'...",2026-03-04T00:28:20.082786

In [12]:
sellers_df.head()

,_id,seller_id,seller_profile,address,products,ratings,performance,last_updated
0,69a8ff7d8aa490a18f20b87c,SELL001,"{'name': 'Seller_1', 'business_type': 'Wholesa...","{'street': 'Shop 279', 'city': 'Bengaluru', 's...","[{'product_id': 'SELL001_PRD1', 'category': 'B...","[{'customer_id': 'CUST118', 'rating': 3, 'revi...","{'total_orders': 920, 'cancelled_orders': 16}",2026-03-04T01:28:30.404844
1,69a8ff7d8aa490a18f20b87d,SELL002,"{'name': 'Seller_2', 'business_type': 'Retail'...","{'street': 'Shop 35', 'city': 'Chennai', 'stat...","[{'product_id': 'SELL002_PRD1', 'category': 'E...","[{'customer_id': 'CUST122', 'rating': 5, 'revi...","{'total_orders': 146, 'cancelled_orders': 5}",2026-03-02T10:28:30.404920
2,69a8ff7d8aa490a18f20b87e,SELL003,"{'name': 'Seller_3', 'business_type': 'Retail'...","{'street': 'Shop 247', 'city': 'Mumbai', 'stat...","[{'product_id': 'SELL003_PRD1', 'category': 'H...","[{'customer_id': 'CUST039', 'rating': 4, 'revi...","{'total_orders': 1845, 'cancelled_orders': 2}",2026-02-26T00:28:30.405011
3,69a8ff7d8aa490a18f20b87f,SELL004,"{'name': 'Seller_4', 'business_type': 'Retail'...","{'street': None, 'city': 'Bengaluru', 'state':...","[{'product_id': 'SELL004_PRD1', 'category': 'E...","[{'customer_id': 'CUST497', 'rating': 5, 'revi...","{'total_orders': 162, 'cancelled_orders': 22}",2026-02-28T17:28:30.405143
4,69a8ff7d8aa490a18f20b880,SELL005,"{'name': 'Seller_5', 'business_type': 'Wholesa...","{'street': 'Shop 53', 'city': 'Bengaluru', 'st...","[{'product_id': 'SELL005_PRD1', 'category': 'H...","[{'customer_id': 'CUST314', 'rating': 3, 'revi...","{'total_orders': 1115, 'cancelled_orders': 50}",2026-03-03T16:28:30.405206

In [13]:
orders_df.head()

,_id,order_id,customer_id,seller_id,order_date,order_status,items,payment,shipping,order_total,last_updated
0,69a8ff7d8aa490a18f20b8f4,ORD0001,CUST498,SELL105,2026-02-13T09:28:40.374751,PLACED,"[{'product_id': 'SELL105_PRD5', 'product_name'...","{'method': 'UPI', 'transaction_id': None, 'pay...","{'delivery_partner': 'BlueDart', 'expected_del...",33993.48,2026-02-14T06:28:40.374751
1,69a8ff7d8aa490a18f20b8f5,ORD0002,CUST223,SELL022,2026-02-22T09:28:40.374846,CANCELLED,"[{'product_id': 'SELL022_PRD5', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'Delhivery', 'expected_de...",94373.34,2026-02-23T09:28:40.374846
2,69a8ff7d8aa490a18f20b8f6,ORD0003,CUST186,SELL081,2026-02-17T09:28:40.374898,SHIPPED,"[{'product_id': 'SELL081_PRD3', 'product_name'...","{'method': 'Credit Card', 'transaction_id': 'T...","{'delivery_partner': 'Ecom Express', 'expected...",91000.23,2026-02-18T11:28:40.374898
3,69a8ff7d8aa490a18f20b8f7,ORD0004,CUST357,SELL012,2026-02-05T09:28:40.374938,CANCELLED,"[{'product_id': 'SELL012_PRD3', 'product_name'...","{'method': 'Credit Card', 'transaction_id': 'T...","{'delivery_partner': 'Delhivery', 'expected_de...",NaN,2026-02-06T07:28:40.374938
4,69a8ff7d8aa490a18f20b8f8,ORD0005,CUST359,SELL120,2026-02-11T09:28:40.374991,NaN,"[{'product_id': 'SELL120_PRD5', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'BlueDart', 'expected_del...",106526.26,2026-02-12T11:28:40.374991

In [14]:
from transform import transform

In [15]:
dir(transform)

['__annotate__',
 '__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__type_params__']

In [16]:
customers_df = transform(customers_df)
customers_df.head(2)

,_id,customer_id,last_updated,_array_index,method,provider,last_used,profile_name,profile_email,profile_phone,...,profile_signup_date,address_current_street,address_current_city,address_current_state,address_current_zip,address_current_country,_source_object_id,is_active,etl_loaded_at,row_hash
0,69a8ff7c8aa490a18f20b688,CUST001,2026-03-06 00:28:20.082640,0,Credit Card,SBI,2026-02-13,Customer_0A1,customer1@example.com,9669660605,...,2026-01-12 09:28:20.082679,NaN,Mumbai,Maharashtra,328425,India,69a8ff7c8aa490a18f20b688,1,2026-03-05 16:15:31.408463,b20881d7d727b9c6d62dcf6dbb67b8cb
1,69a8ff7c8aa490a18f20b689,CUST002,2026-03-03 00:28:20.082706,0,Debit Card,ICICI,2026-02-17,Customer_2,customer2@example.com,9812820684,...,2025-07-20 09:28:20.082716,Street 153,Delhi,Delhi,170929,India,69a8ff7c8aa490a18f20b689,1,2026-03-05 16:15:31.408463,794e250bb3e370a6493d1117c4238976

In [17]:
sellers_df=extract("sellers")

In [18]:
sellers_df_transform=transform(sellers_df)
sellers_df_transform.head(2)

,_id,seller_id,last_updated,_array_index,product_id,category,price,stock,customer_id,rating,...,address_city,address_state,address_zip,address_country,performance_total_orders,performance_cancelled_orders,_source_object_id,is_active,etl_loaded_at,row_hash
0,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,0,SELL001_PRD1,Beauty,7508.93,27.0,CUST118,3,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:31.661159,04f993a59dfb6d2be3cc02b27d1633e7
1,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,1,SELL001_PRD1,Beauty,7508.93,27.0,CUST016,4,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:31.661159,372fe1033db34562ab8245bfbf4bcfd3

In [19]:
sellers_df_transform.duplicated(subset=['seller_id','product_id']).any()

np.True_

In [20]:
sellers_df_transform.duplicated(
    subset=['seller_id','product_id']
).any()

np.True_

In [21]:
orders_df.head(2)

,_id,order_id,customer_id,seller_id,order_date,order_status,items,payment,shipping,order_total,last_updated
0,69a8ff7d8aa490a18f20b8f4,ORD0001,CUST498,SELL105,2026-02-13T09:28:40.374751,PLACED,"[{'product_id': 'SELL105_PRD5', 'product_name'...","{'method': 'UPI', 'transaction_id': None, 'pay...","{'delivery_partner': 'BlueDart', 'expected_del...",33993.48,2026-02-14T06:28:40.374751
1,69a8ff7d8aa490a18f20b8f5,ORD0002,CUST223,SELL022,2026-02-22T09:28:40.374846,CANCELLED,"[{'product_id': 'SELL022_PRD5', 'product_name'...","{'method': 'Debit Card', 'transaction_id': 'TX...","{'delivery_partner': 'Delhivery', 'expected_de...",94373.34,2026-02-23T09:28:40.374846

In [22]:
orders_df_transform=transform(orders_df)
orders_df_transform.head(2)

,_id,order_id,customer_id,seller_id,order_date,order_status,order_total,last_updated,_array_index,product_id,...,discount_amount,payment_method,payment_transaction_id,payment_payment_status,shipping_delivery_partner,shipping_expected_delivery,_source_object_id,is_active,etl_loaded_at,row_hash
0,69a8ff7d8aa490a18f20b8f4,ORD0001,CUST498,SELL105,2026-02-13 09:28:40.374751,PLACED,33993.48,2026-02-14 06:28:40.374751,0,SELL105_PRD5,...,200.0,UPI,NaN,FAILED,BlueDart,2026-02-15,69a8ff7d8aa490a18f20b8f4,1,2026-03-05 16:15:32.156133,065e6313e0fdfed45f9b81177db8194b
1,69a8ff7d8aa490a18f20b8f4,ORD0001,CUST498,SELL105,2026-02-13 09:28:40.374751,PLACED,33993.48,2026-02-14 06:28:40.374751,1,SELL105_PRD2,...,0.0,UPI,NaN,FAILED,BlueDart,2026-02-15,69a8ff7d8aa490a18f20b8f4,1,2026-03-05 16:15:32.156133,85de054209de482535465f3ef2f933e7

In [23]:
sellers_df1=extract("sellers")
sellers_df1.head()

,_id,seller_id,seller_profile,address,products,ratings,performance,last_updated
0,69a8ff7d8aa490a18f20b87c,SELL001,"{'name': 'Seller_1', 'business_type': 'Wholesa...","{'street': 'Shop 279', 'city': 'Bengaluru', 's...","[{'product_id': 'SELL001_PRD1', 'category': 'B...","[{'customer_id': 'CUST118', 'rating': 3, 'revi...","{'total_orders': 920, 'cancelled_orders': 16}",2026-03-04T01:28:30.404844
1,69a8ff7d8aa490a18f20b87d,SELL002,"{'name': 'Seller_2', 'business_type': 'Retail'...","{'street': 'Shop 35', 'city': 'Chennai', 'stat...","[{'product_id': 'SELL002_PRD1', 'category': 'E...","[{'customer_id': 'CUST122', 'rating': 5, 'revi...","{'total_orders': 146, 'cancelled_orders': 5}",2026-03-02T10:28:30.404920
2,69a8ff7d8aa490a18f20b87e,SELL003,"{'name': 'Seller_3', 'business_type': 'Retail'...","{'street': 'Shop 247', 'city': 'Mumbai', 'stat...","[{'product_id': 'SELL003_PRD1', 'category': 'H...","[{'customer_id': 'CUST039', 'rating': 4, 'revi...","{'total_orders': 1845, 'cancelled_orders': 2}",2026-02-26T00:28:30.405011
3,69a8ff7d8aa490a18f20b87f,SELL004,"{'name': 'Seller_4', 'business_type': 'Retail'...","{'street': None, 'city': 'Bengaluru', 'state':...","[{'product_id': 'SELL004_PRD1', 'category': 'E...","[{'customer_id': 'CUST497', 'rating': 5, 'revi...","{'total_orders': 162, 'cancelled_orders': 22}",2026-02-28T17:28:30.405143
4,69a8ff7d8aa490a18f20b880,SELL005,"{'name': 'Seller_5', 'business_type': 'Wholesa...","{'street': 'Shop 53', 'city': 'Bengaluru', 'st...","[{'product_id': 'SELL005_PRD1', 'category': 'H...","[{'customer_id': 'CUST314', 'rating': 3, 'revi...","{'total_orders': 1115, 'cancelled_orders': 50}",2026-03-03T16:28:30.405206

In [24]:
seller_df1_transform1=transform(sellers_df1)
seller_df1_transform1.head()

,_id,seller_id,last_updated,_array_index,product_id,category,price,stock,customer_id,rating,...,address_city,address_state,address_zip,address_country,performance_total_orders,performance_cancelled_orders,_source_object_id,is_active,etl_loaded_at,row_hash
0,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,0,SELL001_PRD1,Beauty,7508.93,27.0,CUST118,3,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,04f993a59dfb6d2be3cc02b27d1633e7
1,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,1,SELL001_PRD1,Beauty,7508.93,27.0,CUST016,4,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,372fe1033db34562ab8245bfbf4bcfd3
2,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,0,SELL001_PRD2,Clothing,6010.46,133.0,CUST118,3,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,7783fd857f8a4c1a1d9a79b3135ea1c1
3,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,1,SELL001_PRD2,Clothing,6010.46,133.0,CUST016,4,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,c6fb1fb51738ee228eea9e1cc3238968
4,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,0,SELL001_PRD3,Beauty,22244.22,2.0,CUST118,3,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,bbe73368d58e029e49fc24b8de05f7db

In [25]:
seller_df1_transform1.duplicated(
    subset=['_source_object_id','_array_index']
).any()

np.True_

In [26]:
seller_df1_transform1[
    seller_df1_transform1.duplicated(
        subset=['seller_id','product_id'],
        keep=False
    )
].sort_values(['seller_id','product_id'])

,_id,seller_id,last_updated,_array_index,product_id,category,price,stock,customer_id,rating,...,address_city,address_state,address_zip,address_country,performance_total_orders,performance_cancelled_orders,_source_object_id,is_active,etl_loaded_at,row_hash
0,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,0,SELL001_PRD1,Beauty,7508.93,27.0,CUST118,3,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,04f993a59dfb6d2be3cc02b27d1633e7
1,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,1,SELL001_PRD1,Beauty,7508.93,27.0,CUST016,4,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,372fe1033db34562ab8245bfbf4bcfd3
2,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,0,SELL001_PRD2,Clothing,6010.46,133.0,CUST118,3,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,7783fd857f8a4c1a1d9a79b3135ea1c1
3,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,1,SELL001_PRD2,Clothing,6010.46,133.0,CUST016,4,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,c6fb1fb51738ee228eea9e1cc3238968
4,69a8ff7d8aa490a18f20b87c,SELL001,2026-03-04 01:28:30.404844,0,SELL001_PRD3,Beauty,22244.22,2.0,CUST118,3,...,Bengaluru,Karnataka,451935,India,920,16.0,69a8ff7d8aa490a18f20b87c,1,2026-03-05 16:15:32.594455,bbe73368d58e029e49fc24b8de05f7db
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1933,69a8ff7d8aa490a18f20b8f3,SELL120,2026-03-02 14:28:30.418282,1,SELL120_PRD3,Clothing,13858.48,193.0,CUST043,5,...,Kolkata,West Bengal,852777,India,250,22.0,69a8ff7d8aa490a18f20b8f3,1,2026-03-05 16:15:32.594455,7aa9a1e28e6ca76f5498d2ceadfbf748
1934,69a8ff7d8aa490a18f20b8f3,SELL120,2026-03-02 14:28:30.418282,0,SELL120_PRD4,Beauty,8496.40,181.0,CUST482,4,...,Kolkata,West Bengal,852777,India,250,22.0,69a8ff7d8aa490a18f20b8f3,1,2026-03-05 16:15:32.594455,a689360180033be4420e9617d9da6917
1935,69a8ff7d8aa490a18f20b8f3,SELL120,2026-03-02 14:28:30.418282,1,SELL120_PRD4,Beauty,8496.40,181.0,CUST043,5,...,Kolkata,West Bengal,852777,India,250,22.0,69a8ff7d8aa490a18f20b8f3,1,2026-03-05 16:15:32.594455,90ed1cacd4e535a2451f0d7f13fc0232
1936,69a8ff7d8aa490a18f20b8f3,SELL120,2026-03-02 14:28:30.418282,0,SELL120_PRD5,Electronics,25586.54,73.0,CUST482,4,...,Kolkata,West Bengal,852777,India,250,22.0,69a8ff7d8aa490a18f20b8f3,1,2026-03-05 16:15:32.594455,61874b519137f49c26170959e8b8ae91
1937,69a8ff7d8aa490a18f20b8f3,SELL120,2026-03-02 14:28:30.418282,1,SELL120_PRD5,Electronics,25586.54,73.0,CUST043,5,...,Kolkata,West Bengal,852777,India,250,22.0,69a8ff7d8aa490a18f20b8f3,1,2026-03-05 16:15:32.594455,d5b809195be41e11eeef662687088be0

In [27]:
from load import test_connection, full_load
import pandas as pd

ImportError: cannot import name 'test_connection' from 'load' (c:\work\data-migration-aparna\load.py)

In [ ]:
test_connection()

✅ MySQL Connection Successful

In [ ]:
from load import test_connection
test_connection()

✅ MySQL Connection Successful

In [ ]:
import sys
print(sys.executable)

c:\Users\aparna.b.b_coditas\AppData\Local\Programs\Python\Python314\python.exe

In [ ]:
import mysql.connector
print(mysql.connector.__version__)

9.6.0

In [ ]:
customers_df.duplicated(subset='customer_id').any()

np.False_

In [ ]:
seller_df1_transform1.head()

NameError: name 'seller_df1_transform1' is not defined

In [ ]:
seller_df1_transform1.duplicated(subset=['_source_object_id','row_hash']).any()

np.False_

In [ ]:
duplicates = seller_df1_transform1[seller_df1_transform1.duplicated(
    subset=['_source_object_id','_array_index'], keep=False
)]
print(duplicates)

                           _id seller_id               last_updated  \
0     69a8ff7d8aa490a18f20b87c   SELL001 2026-03-04 01:28:30.404844
1     69a8ff7d8aa490a18f20b87c   SELL001 2026-03-04 01:28:30.404844
2     69a8ff7d8aa490a18f20b87c   SELL001 2026-03-04 01:28:30.404844
3     69a8ff7d8aa490a18f20b87c   SELL001 2026-03-04 01:28:30.404844
4     69a8ff7d8aa490a18f20b87c   SELL001 2026-03-04 01:28:30.404844
...                        ...       ...                        ...
1933  69a8ff7d8aa490a18f20b8f3   SELL120 2026-03-02 14:28:30.418282
1934  69a8ff7d8aa490a18f20b8f3   SELL120 2026-03-02 14:28:30.418282
1935  69a8ff7d8aa490a18f20b8f3   SELL120 2026-03-02 14:28:30.418282
1936  69a8ff7d8aa490a18f20b8f3   SELL120 2026-03-02 14:28:30.418282
1937  69a8ff7d8aa490a18f20b8f3   SELL120 2026-03-02 14:28:30.418282

      _array_index    product_id     category     price  stock customer_id  \
0                0  SELL001_PRD1       Beauty   7508.93   27.0     CUST118
1                1  SELL001_PRD1       Beauty   7508.93   27.0     CUST016
2                0  SELL001_PRD2     Clothing   6010.46  133.0     CUST118
3                1  SELL001_PRD2     Clothing   6010.46  133.0     CUST016
4                0  SELL001_PRD3       Beauty  22244.22    2.0     CUST118
...            ...           ...          ...       ...    ...         ...
1933             1  SELL120_PRD3     Clothing  13858.48  193.0     CUST043
1934             0  SELL120_PRD4       Beauty   8496.40  181.0     CUST482
1935             1  SELL120_PRD4       Beauty   8496.40  181.0     CUST043
1936             0  SELL120_PRD5  Electronics  25586.54   73.0     CUST482
1937             1  SELL120_PRD5  Electronics  25586.54   73.0     CUST043

      rating  ... address_city address_state address_zip address_country  \
0          3  ...    Bengaluru     Karnataka      451935           India
1          4  ...    Bengaluru     Karnataka      451935           India
2          3  ...    Bengaluru     Karnataka      451935           India
3          4  ...    Bengaluru     Karnataka      451935           India
4          3  ...    Bengaluru     Karnataka      451935           India
...      ...  ...          ...           ...         ...             ...
1933       5  ...      Kolkata   West Bengal      852777           India
1934       4  ...      Kolkata   West Bengal      852777           India
1935       5  ...      Kolkata   West Bengal      852777           India
1936       4  ...      Kolkata   West Bengal      852777           India
1937       5  ...      Kolkata   West Bengal      852777           India

     performance_total_orders performance_cancelled_orders  \
0                         920                         16.0
1                         920                         16.0
2                         920                         16.0
3                         920                         16.0
4                         920                         16.0
...                       ...                          ...
1933                      250                         22.0
1934                      250                         22.0
1935                      250                         22.0
1936                      250                         22.0
1937                      250                         22.0

             _source_object_id is_active              etl_loaded_at  \
0     69a8ff7d8aa490a18f20b87c         1 2026-03-05 13:44:38.187148
1     69a8ff7d8aa490a18f20b87c         1 2026-03-05 13:44:38.187148
2     69a8ff7d8aa490a18f20b87c         1 2026-03-05 13:44:38.187148
3     69a8ff7d8aa490a18f20b87c         1 2026-03-05 13:44:38.187148
4     69a8ff7d8aa490a18f20b87c         1 2026-03-05 13:44:38.187148
...                        ...       ...                        ...
1933  69a8ff7d8aa490a18f20b8f3         1 2026-03-05 13:44:38.187148
1934  69a8ff7d8aa490a18f20b8f3         1 2026-03-05 13:44:38.187148
1935  69a8ff7d8aa490a18f20b8f3         1 2026-03-05 13:44:38.187148
1936  69a8ff7d8aa490a18f20b8f3         1 2026-03-05 13:44:38.187148
1937  69a8ff7d8aa490a18f20b8f3         1 2026-03-05 13:44:38.187148

                              row_hash
0     04f993a59dfb6d2be3cc02b27d1633e7
1     372fe1033db34562ab8245bfbf4bcfd3
2     7783fd857f8a4c1a1d9a79b3135ea1c1
3     c6fb1fb51738ee228eea9e1cc3238968
4     bbe73368d58e029e49fc24b8de05f7db
...                                ...
1933  7aa9a1e28e6ca76f5498d2ceadfbf748
1934  a689360180033be4420e9617d9da6917
1935  90ed1cacd4e535a2451f0d7f13fc0232
1936  61874b519137f49c26170959e8b8ae91
1937  d5b809195be41e11eeef662687088be0

[1938 rows x 26 columns]

In [ ]:
orders_df_transform.head()

,_id,order_id,customer_id,seller_id,order_date,order_status,order_total,last_updated,_array_index,product_id,...,discount_amount,payment_method,payment_transaction_id,payment_payment_status,shipping_delivery_partner,shipping_expected_delivery,_source_object_id,is_active,etl_loaded_at,row_hash
0,69a8ff7d8aa490a18f20b8f4,ORD0001,CUST498,SELL105,2026-02-13 09:28:40.374751,PLACED,33993.48,2026-02-14 06:28:40.374751,0,SELL105_PRD5,...,200.0,UPI,NaN,FAILED,BlueDart,2026-02-15,69a8ff7d8aa490a18f20b8f4,1,2026-03-05 13:44:37.238202,065e6313e0fdfed45f9b81177db8194b
1,69a8ff7d8aa490a18f20b8f4,ORD0001,CUST498,SELL105,2026-02-13 09:28:40.374751,PLACED,33993.48,2026-02-14 06:28:40.374751,1,SELL105_PRD2,...,0.0,UPI,NaN,FAILED,BlueDart,2026-02-15,69a8ff7d8aa490a18f20b8f4,1,2026-03-05 13:44:37.238202,85de054209de482535465f3ef2f933e7
2,69a8ff7d8aa490a18f20b8f5,ORD0002,CUST223,SELL022,2026-02-22 09:28:40.374846,CANCELLED,94373.34,2026-02-23 09:28:40.374846,0,SELL022_PRD5,...,0.0,Debit Card,TXN959369,SUCCESS,Delhivery,2026-02-28,69a8ff7d8aa490a18f20b8f5,1,2026-03-05 13:44:37.238202,46aa60cae82f59cdc1bdff2fda62b695
3,69a8ff7d8aa490a18f20b8f5,ORD0002,CUST223,SELL022,2026-02-22 09:28:40.374846,CANCELLED,94373.34,2026-02-23 09:28:40.374846,1,SELL022_PRD1,...,200.0,Debit Card,TXN959369,SUCCESS,Delhivery,2026-02-28,69a8ff7d8aa490a18f20b8f5,1,2026-03-05 13:44:37.238202,c1c5975e0ff919b1ee76d3353405383d
4,69a8ff7d8aa490a18f20b8f5,ORD0002,CUST223,SELL022,2026-02-22 09:28:40.374846,CANCELLED,94373.34,2026-02-23 09:28:40.374846,2,SELL022_PRD7,...,200.0,Debit Card,TXN959369,SUCCESS,Delhivery,2026-02-28,69a8ff7d8aa490a18f20b8f5,1,2026-03-05 13:44:37.238202,7a1d032602db912ccb682ef0343f0e1b

In [ ]:
orders_df_transform.duplicated(subset=['_source_object_id','row_hash']).any()

np.False_

In [ ]:
customers_df=extract("customers")
customers_df_transformed=transform(customers_df)
customers_df_transformed.head()

,_id,customer_id,last_updated,_array_index,method,provider,last_used,profile_name,profile_email,profile_phone,...,profile_signup_date,address_current_street,address_current_city,address_current_state,address_current_zip,address_current_country,_source_object_id,is_active,etl_loaded_at,row_hash
0,69a8ff7c8aa490a18f20b688,CUST001,2026-03-05 00:28:20.082640,0,Credit Card,SBI,2026-02-13,Customer_A1,customer1@example.com,9669660605,...,2026-01-12 09:28:20.082679,NaN,Mumbai,Maharashtra,328425,India,69a8ff7c8aa490a18f20b688,1,2026-03-05 13:50:53.637056,15329f11eafaf04685f61c79dd1d2d02
1,69a8ff7c8aa490a18f20b689,CUST002,2026-03-03 00:28:20.082706,0,Debit Card,ICICI,2026-02-17,Customer_2,customer2@example.com,9812820684,...,2025-07-20 09:28:20.082716,Street 153,Delhi,Delhi,170929,India,69a8ff7c8aa490a18f20b689,1,2026-03-05 13:50:53.637056,794e250bb3e370a6493d1117c4238976
2,69a8ff7c8aa490a18f20b68a,CUST003,2026-03-01 00:28:20.082744,0,Credit Card,ICICI,2026-02-28,Customer_3,customer3@example.com,9685058192,...,2025-10-21 09:28:20.082753,NaN,Chennai,Tamil Nadu,228827,India,69a8ff7c8aa490a18f20b68a,1,2026-03-05 13:50:53.637056,e6622357b508a57bbbe716d338d8abc6
3,69a8ff7c8aa490a18f20b68b,CUST004,2026-03-03 00:28:20.082767,0,Credit Card,ICICI,2026-03-04,Customer_4,customer4@example.com,9913619298,...,2026-02-03 09:28:20.082772,Street 200,Pune,Maharashtra,510215,India,69a8ff7c8aa490a18f20b68b,1,2026-03-05 13:50:53.637056,5c4f80f7175611e0912e47e3289a69f6
4,69a8ff7c8aa490a18f20b68c,CUST005,2026-03-04 00:28:20.082786,0,Credit Card,ICICI,2026-02-12,Customer_5,customer5@example.com,9374749217,...,2026-01-12 09:28:20.082792,NaN,Hyderabad,Telangana,491841,India,69a8ff7c8aa490a18f20b68c,1,2026-03-05 13:50:53.637056,db014ca55ca00b20ce97afce05562f0d

In [ ]:
customers_df_transformed.duplicated(subset=['_source_object_id','row_hash']).any()

np.False_

In [ ]:
seller_df1_transform1[['_source_object_id','_array_index']]

             _source_object_id  _array_index
0     69a8ff7d8aa490a18f20b87c             0
1     69a8ff7d8aa490a18f20b87c             1
2     69a8ff7d8aa490a18f20b87c             0
3     69a8ff7d8aa490a18f20b87c             1
4     69a8ff7d8aa490a18f20b87c             0
...                        ...           ...
1933  69a8ff7d8aa490a18f20b8f3             1
1934  69a8ff7d8aa490a18f20b8f3             0
1935  69a8ff7d8aa490a18f20b8f3             1
1936  69a8ff7d8aa490a18f20b8f3             0
1937  69a8ff7d8aa490a18f20b8f3             1

[1938 rows x 2 columns]